export const services: string[] = [
    "Audiometría",
    "Clínica Médica",
    "Demanda Espontánea",
    "Dermatología",
    "Diabetología",
    "Diagnóstico por imágenes",
    "Ecografías",
    "Electrocardiograma",
    "Estimulación Temprana",
    "Ginecología",
    "Oftalmología",
    "Oftalmología Infantil",
    "Otorrinolaringología",
    "Psicopedagogía",
    "Psiquiatría",
    "Ecodiagnóstico",
    "Enfermería",
    "Fonoaudiología",
    "IVE/ILE",
    "Laboratorio",
    "Medicina General/Fliar",
    "Nutrición",
    "Obstetricia",
    "Odontología",
    "PAP",
    "Pediatría",
    "Psicología",
    "Radiografías",
    "Talleres",
    "Trabajo Social",
    "Traumatología",
    "Salud Pública"

]